### ISSUE TITLE
Issue since 0.14 release

### ISSUE THREAD

**Issue by dbecker215** [nkbt/react-interval#3]
I'm using gulp and elemental-UI which uses react-interval as a dependency. We're running React 0.13 and when I try to install via npm I'm getting "Cannot find module 'react-addons-pure-render-mixin' ". This appears to be thrown at line 13 of ReactInterval.js. When I try to install 'react-addons-pure-render-mixin'  I get a compatibility issue that says 'react-addons-pure-render-mixin' requires React 0.14. It appears that react-interval is supposed to be compatible with 0.13 & 0.14, but this one reference is breaking my gulp task which prevents usage. Am I missing something as to making it compatible with 0.13? Or is 0.13 no longer supported?

**Comment by nkbt** [comment]
Ouch, I guess my React 13 testing went in a bit wrong way, I will fix this
asap. Thank you for report

**Comment by nkbt** [comment]
Fixed with 69cc9f5
Published as 1.2.1 patch release

**Comment by dbecker215** [comment]
Great! Thank you!
